import "dotenv/config";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import express from "express";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import authRoutes from "../routes/auth.routes";
import propertyRoutes from "../routes/property.routes";
import verificationRoutes from "../routes/advisor.routes";
import adminRoutes from "../routes/admin.routes";
import documentRoutes from "../routes/document.routes";
import dealRoutes from "../routes/deal.routes";
import { User } from "../models/User.model";
import { Property } from "../models/Property.model";
import { PropertyDocument } from "../models/Document.model";

async function main() {
  const dbName = `malikse_workflow_test_${randomUUID().replace(/-/g, "")}`;
  await mongoose.connect(process.env.MONGO_URI || "mongodb://localhost:27017/malikse", { dbName });
  const app = express();
  app.use(express.json());
  app.use("/auth", authRoutes); app.use("/properties", propertyRoutes); app.use("/verification", verificationRoutes); app.use("/admin", adminRoutes); app.use("/documents", documentRoutes);
  app.use("/deals", dealRoutes);
  const server = app.listen(0, "127.0.0.1");
  await new Promise<void>(resolve => server.once("listening", resolve));
  const port = (server.address() as any).port;
  const base = `http://127.0.0.1:${port}`;
  let checks = 0;
  const request = async (route: string, token?: string, body?: object, expected = 200, method = body ? "POST" : "GET") => {
    const response = await fetch(base + route, { method, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
    const data: any = await response.json();
    assert.equal(response.status, expected, `${method} ${route}: ${JSON.stringify(data)}`);
    checks++;
    return data;
  };
  const password = "workflow-test-password";
  const login = async (mobile: string) => (await request("/auth/login", undefined, { mobile, password })).accessToken;
  try {
    await User.create({ name: "Test Admin", mobile: "9000000001", role: "admin", passwordHash: await bcrypt.hash(password, 10) });
    const admin = await login("9000000001");
    const sellerAccount = await request("/auth/register", undefined, { name: "Test Seller", mobile: "9000000002", password, role: "admin" }, 201);
    assert.equal(sellerAccount.user.role, "user");
    const seller = sellerAccount.accessToken;
    const outsider = (await request("/auth/register", undefined, { name: "Other Seller", mobile: "9000000003", password }, 201)).accessToken;
    const input = { title: "Workflow test land", type: "land", location: { state: "Bihar", district: "Patna", lat: 25.6, lng: 85.1 }, price: 1000000, totalArea: 1000, sellableArea: 900, parcelPoints: [{ lat: 25.6, lng: 85.1 }, { lat: 25.61, lng: 85.1 }, { lat: 25.6, lng: 85.11 }] };
    await request("/properties", seller, input, 403);
    await request("/auth/kyc/demo", seller, {});
    const draft = await request("/properties", seller, { ...input, status: "verified", badges: { fullyVerified: true }, assignedAdvisorId: sellerAccount.user.id }, 201);
    assert.equal(draft.status, "draft"); assert.equal(draft.badges.fullyVerified, false); assert.equal(draft.assignedAdvisorId, undefined);
    const id = draft._id;
    await request(`/properties/${id}`, undefined, undefined, 404);
    await request(`/properties/${id}/workspace`, outsider, undefined, 403);
    await request(`/documents?propertyId=${id}`, outsider, undefined, 403);
    await request(`/properties/${id}/submit`, seller, {}, 400);
    const pending = await request(`/properties/${id}/submit`, seller, { consent: true });
    assert.equal(pending.status, "pending"); assert.equal(pending.assignedAdvisorId, null);
    await request(`/properties/${id}/submit`, seller, { consent: true }, 409);
    await request(`/properties/${id}`, seller, { price: 1 }, 409, "PATCH");
    assert.equal((await request("/properties/search")).length, 0);
    await request(`/deals/${id}/offer`, seller, { amount: 100 }, 409);

    const advisorAccount = await request("/admin/staff", admin, { role: "advisor", name: "Test Advisor", mobile: "9000000004", password }, 201);
    await request("/admin/staff", admin, { role: "verifier", name: "Test Verifier", mobile: "9000000005", password }, 201);
    await request("/admin/staff", admin, { role: "advisor", name: "Other Advisor", mobile: "9000000006", password }, 201);
    const advisor = await login("9000000004"), verifier = await login("9000000005"), otherAdvisor = await login("9000000006");
    const unassigned = await request("/verification/my-tasks", advisor);
    assert.equal(unassigned.length, 1); assert.equal(unassigned[0].ownerId, undefined);
    await request(`/verification/${id}/claim`, advisor, {});
    await request(`/verification/${id}/claim`, otherAdvisor, {}, 409);
    await request(`/properties/${id}/workspace`, otherAdvisor, undefined, 403);
    const checklist = { ownership: true, location: true, boundaries: true, area: true, disclosures: true, documentsReviewed: true, advisorReport: true };
    const approval = { decision: "approve", notes: "Checked property information", signature: "Test Advisor", checklist };
    await request(`/verification/${id}/report`, seller, approval, 403);
    await request(`/verification/${id}/report`, verifier, approval, 403);
    await request(`/verification/${id}/report`, advisor, { ...approval, checklist: {} }, 400);
    await request(`/verification/${id}/report`, advisor, { ...approval, decision: "correction", notes: "Correct the property area" });
    await request(`/properties/${id}`, seller, { sellableArea: 850, status: "verified", badges: { fullyVerified: true } }, 200, "PATCH");
    const corrected = await request(`/properties/${id}/workspace`, seller);
    assert.equal(corrected.status, "correction_required");
    await request(`/properties/${id}/submit`, seller, { consent: true });
    const stageTwo = await request(`/verification/${id}/report`, advisor, approval);
    assert.equal(stageTwo.status, "advisor_verified"); assert.equal(stageTwo.badges.fullyVerified, false); assert.equal(stageTwo.badges.documentsChecked, false);
    await request(`/verification/${id}/report`, advisor, approval, 409);
    assert.equal((await request("/properties/search")).length, 0);
    const verifierQueue = await request("/verification/my-tasks", verifier);
    assert.equal(verifierQueue[0]._id, id);
    await request(`/verification/${id}/report`, verifier, { ...approval, decision: "correction", notes: "Clarify the boundary description", signature: "Test Verifier" });
    await request(`/properties/${id}`, seller, { boundary: "North road, south field" }, 200, "PATCH");
    await request(`/properties/${id}/submit`, seller, { consent: true });
    await request(`/verification/${id}/report`, verifier, approval, 403);
    await request(`/verification/${id}/report`, advisor, approval);
    const results = await Promise.all([1, 2].map(() => fetch(`${base}/verification/${id}/report`, { method: "POST", headers: { Authorization: `Bearer ${verifier}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...approval, signature: "Test Verifier" }) })));
    assert.deepEqual(results.map(result => result.status).sort(), [200, 409]);
    const published = await request(`/properties/${id}`);
    assert.equal(published.status, "verified"); assert.equal(published.badges.fullyVerified, true);
    for (const field of ["ownerId", "documents", "verificationHistory", "advisorReview", "verifierReview", "khata"]) assert.equal(published[field], undefined);
    assert.equal((await request("/properties/search")).length, 1);
    await request(`/deals/${id}/offer`, seller, { amount: 100 }, 400);
    await request(`/deals/${id}/offer`, outsider, { amount: 100 }, 403);
    await request("/auth/kyc/demo", outsider, {});
    await request(`/deals/${id}/offer`, outsider, { amount: -100 }, 400);
    await request(`/deals/${id}/offer`, outsider, { amount: 900000 }, 201);
    assert.equal((await request("/properties/search?budgetMax=100")).length, 0);
    await request(`/properties/${id}`, seller, { price: 2 }, 409, "PATCH");
    await request(`/admin/properties/${id}/assign`, admin, { staffId: advisorAccount.id }, 409);
    const tracked = await request(`/properties/${id}/workspace`, admin);
    assert.ok(tracked.verificationHistory.some((event: any) => event.report?.decision === "correction"));
    assert.equal(tracked.verificationHistory.filter((event: any) => event.toStatus === "verified").length, 1);

    const second = await request("/properties", seller, input, 201);
    const multipart = new FormData();
    multipart.append("propertyId", second._id); multipart.append("type", "Registry"); multipart.append("file", new Blob(["Test ownership document"]), "test.txt");
    const uploaded = await fetch(base + "/documents", { method: "POST", headers: { Authorization: `Bearer ${seller}` }, body: multipart });
    assert.equal(uploaded.status, 201, await uploaded.text());
    const documents = await request(`/documents?propertyId=${second._id}`, seller);
    assert.equal(documents.length, 1);
    const download = await fetch(documents[0].fileUrl);
    assert.equal(download.status, 200); assert.equal(await download.text(), "Test ownership document");
    assert.equal((await fetch(documents[0].fileUrl.split("?")[0])).status, 403);
    await request(`/documents?propertyId=${second._id}`, outsider, undefined, 403);
    const autoAssigned = await request(`/properties/${second._id}/submit`, seller, { consent: true });
    assert.ok(autoAssigned.assignedAdvisorId);
    await request(`/admin/properties/${second._id}/assign`, admin, { staffId: advisorAccount.id });
    await request(`/verification/${second._id}/report`, advisor, { ...approval, decision: "reject", notes: "Ownership details do not match" });
    await request(`/properties/${second._id}/submit`, seller, { consent: true }, 409);
    assert.equal((await request("/properties/search")).length, 1);
    assert.equal(await Property.countDocuments(), 2);
    console.log(`Workflow passed: ${checks} HTTP assertions plus assignment, correction loops, concurrent decisions, optional documents, protected downloads, publication and audit checks.`);
  } finally {
    const docs = await PropertyDocument.find();
    for (const doc of docs) {
      if (/^[a-f0-9-]+\.[a-z0-9]+$/i.test(doc.fileUrl)) fs.rmSync(path.join(__dirname, "../../uploads", path.basename(doc.fileUrl)), { force: true });
    }
    assert.ok(mongoose.connection.name.startsWith("malikse_workflow_test_"));
    await mongoose.connection.dropDatabase();
    await mongoose.disconnect();
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
  }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
